version: '3'
services:
  bot:
    build: './'
#  mongodb:
#    image: mongo:5.0.11
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=user
#      - MONGO_INITDB_ROOT_PASSWORD=password
#    volumes:
#      - ./mongo-volume:/data/db
#    ports:
#      - "27017:27017"