version: '3'
services:
  bot:
    build: './'
    environment:
      - LURKER_BOT_TOKEN=${LURKER_BOT_TOKEN}
      - LURKER_BOT_DB=${LURKER_BOT_DB}
      - env=${env}
    logging:
      options:
        max-file: "3"
        max-size: "30m"
#  mongodb:
#    image: mongo:5.0.11
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=user
#      - MONGO_INITDB_ROOT_PASSWORD=password
#    volumes:
#      - ./mongo-volume:/data/db
#    ports:
#      - "27017:27017"
