name: Build and Test
on: [ pull_request ]
jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:

      # Setup Java 1.8 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Gradlew is now executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build application
      - name: Test and Build
        run: ./gradlew build